// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Chargement explicite du ".env" à la RACINE DU MONOREPO (pas celui de
// `backend/`, qui n'existe pas) : ce fichier de config est invoqué avec
// `process.cwd()` pointant sur `backend/` (scripts `npm run ... --workspace=backend`),
// jamais sur la racine — `import "dotenv/config"` seul (résolu relatif à
// `process.cwd()`) ne trouverait donc pas le fichier. Chemin calculé
// relatif à CE fichier (`__dirname`), robuste quel que soit le répertoire
// d'où la commande est lancée. Voir CLAUDE.md "Monorepo backend/frontend"
// pour le choix du ".env" unique à la racine, partagé avec Next.js et
// Docker Compose.
import path from "node:path";
import dotenv from "dotenv";
dotenv.config({ path: path.resolve(__dirname, "../.env") });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
